version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
  wordpress:
    build:
      context: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
networks:
  inception_network: